# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('sort_order', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField()),
                ('destacada', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='photos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalNoti.Categoria')),
            ],
        ),
    ]
